import { Startup, Category, Testimonial, Article, PlatformStats } from '../types';

export const categories: Category[] = [
  { id: '1', name: 'Technology', icon: 'Cpu', count: 142 },
  { id: '2', name: 'AI', icon: 'Brain', count: 98 },
  { id: '3', name: 'Healthcare', icon: 'HeartPulse', count: 74 },
  { id: '4', name: 'FinTech', icon: 'Wallet', count: 115 },
  { id: '5', name: 'EdTech', icon: 'GraduationCap', count: 63 },
  { id: '6', name: 'Green Energy', icon: 'Leaf', count: 88 },
  { id: '7', name: 'E-commerce', icon: 'ShoppingBag', count: 104 },
  { id: '8', name: 'Consumer Products', icon: 'Sparkles', count: 52 },
];

export const platformStats: PlatformStats = {
  raised: '$250M+',
  investors: '15K+',
  fundedStartups: '1,200+',
  successRate: '98%',
};

export const startups: Startup[] = [
  {
    id: 's1',
    name: 'AeroLux Grid',
    tagline: 'Decentralized next-generation clean energy distribution using intelligent smart-grid mesh.',
    description: 'AeroLux Grid is redefining clean energy availability for micro-communities. Our smart-grid tech dynamically routes surplus energy to grid clusters in real-time, reducing transmission waste by 40%.',
    logo: 'https://images.unsplash.com/photo-1516849841032-87cbac4d88f7?auto=format&fit=crop&w=100&h=100&q=80',
    coverImage: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=800&q=80',
    founder: 'Sophia Varga',
    founderImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&h=150&q=80',
    industry: 'Green Energy',
    fundingGoal: 1500000,
    amountRaised: 1245000,
    daysLeft: 12,
    minInvestment: 500,
    expectedEquity: 0.12,
    location: 'Munich, Germany',
    teamSize: 18,
    monthlyRevenue: 45000,
    customers: 3400,
    category: 'Green Energy',
    backers: 890,
    story: 'Founded in 2024, AeroLux has successfully deployed pilot grids across 14 municipal districts. We are scaling production of our proprietary GridNode-V2 routers and seeking community-driven backing to deploy in 50 more cities before the winter peak.',
    fundingTimeline: [
      { month: 'Jan', amount: 200000 },
      { month: 'Feb', amount: 350000 },
      { month: 'Mar', amount: 580000 },
      { month: 'Apr', amount: 800000 },
      { month: 'May', amount: 1050000 },
      { month: 'Jun', amount: 1245000 },
    ],
  },
  {
    id: 's2',
    name: 'Cortex.ai',
    tagline: 'Autonomous AI agents executing secure financial operations and multi-tier auditing.',
    description: 'Cortex.ai delivers enterprise-grade autonomous agents capable of performing complex compliance, accounting, and multi-signature operations securely using zero-knowledge proofs.',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=100&h=100&q=80',
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    founder: 'Marcus Vance',
    founderImage: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=150&h=150&q=80',
    industry: 'AI',
    fundingGoal: 2000000,
    amountRaised: 1890000,
    daysLeft: 6,
    minInvestment: 1000,
    expectedEquity: 0.08,
    location: 'San Francisco, USA',
    teamSize: 24,
    monthlyRevenue: 120000,
    customers: 85,
    category: 'AI',
    backers: 1240,
    story: 'Cortex.ai was created to relieve finance teams of routine auditing. Our AI agents operate within secure cloud enclaves, automating compliance with 99.9% accuracy. This funding round allows us to integrate our SDK directly into major global banking portals.',
    fundingTimeline: [
      { month: 'Jan', amount: 300000 },
      { month: 'Feb', amount: 650000 },
      { month: 'Mar', amount: 1000000 },
      { month: 'Apr', amount: 1400000 },
      { month: 'May', amount: 1700000 },
      { month: 'Jun', amount: 1890000 },
    ],
  },
  {
    id: 's3',
    name: 'NovaPulse Biotech',
    tagline: 'Non-invasive continuous glucose and metabolic tracking via biometric infrared sensors.',
    description: 'NovaPulse is building the future of wearable metabolic telemetry. Our optical band tracks multi-spectrum biomarkers through the skin without needle punctures or patch replacements.',
    logo: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=100&h=100&q=80',
    coverImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    founder: 'Dr. Helen Chen',
    founderImage: 'https://images.unsplash.com/photo-1594744803329-e58b31de215f?auto=format&fit=crop&w=150&h=150&q=80',
    industry: 'Healthcare',
    fundingGoal: 3000000,
    amountRaised: 1420000,
    daysLeft: 28,
    minInvestment: 250,
    expectedEquity: 0.15,
    location: 'Boston, USA',
    teamSize: 15,
    monthlyRevenue: 15000,
    customers: 500,
    category: 'Healthcare',
    backers: 2150,
    story: 'NovaPulse Biotech spent 4 years in clinical development. With FDA Phase II approval imminent, we are moving to mass scale production of our wearable sensors. Backing us helps us democratize preventative care.',
    fundingTimeline: [
      { month: 'Jan', amount: 100000 },
      { month: 'Feb', amount: 300000 },
      { month: 'Mar', amount: 600000 },
      { month: 'Apr', amount: 900000 },
      { month: 'May', amount: 1200000 },
      { month: 'Jun', amount: 1420000 },
    ],
  },
  {
    id: 's4',
    name: 'PayFlow Nexus',
    tagline: 'Real-time multi-currency B2B settlement infrastructure with zero FX markups.',
    description: 'PayFlow Nexus provides modern corporate treasury tools that settle cross-border B2B invoices instantly. We eliminate traditional intermediary correspondent banking fees.',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=100&h=100&q=80',
    coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    founder: 'Liam Gallagher',
    founderImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&h=150&q=80',
    industry: 'FinTech',
    fundingGoal: 1200000,
    amountRaised: 980000,
    daysLeft: 14,
    minInvestment: 500,
    expectedEquity: 0.10,
    location: 'London, UK',
    teamSize: 20,
    monthlyRevenue: 85000,
    customers: 410,
    category: 'FinTech',
    backers: 730,
    story: 'Cross-border B2B trade is slow and expensive. PayFlow Nexus leverages localized liquidity vaults and automated ledger systems to process B2B payments in under 5 seconds. We have transacted $80M in volume to date.',
    fundingTimeline: [
      { month: 'Jan', amount: 150000 },
      { month: 'Feb', amount: 320000 },
      { month: 'Mar', amount: 500000 },
      { month: 'Apr', amount: 720000 },
      { month: 'May', amount: 880000 },
      { month: 'Jun', amount: 980000 },
    ],
  },
  {
    id: 's5',
    name: 'LearnSphere Studio',
    tagline: 'Immersive VR classrooms bringing experiential learning to global curriculums.',
    description: 'LearnSphere is an interactive educational metaverse. Students run virtual physics experiments and explore historical events in fully rendered, collaborative 3D spaces.',
    logo: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=100&h=100&q=80',
    coverImage: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&w=800&q=80',
    founder: 'Maya Patel',
    founderImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&h=150&q=80',
    industry: 'EdTech',
    fundingGoal: 800000,
    amountRaised: 420000,
    daysLeft: 22,
    minInvestment: 150,
    expectedEquity: 0.08,
    location: 'Austin, USA',
    teamSize: 12,
    monthlyRevenue: 30000,
    customers: 8500,
    category: 'EdTech',
    backers: 1550,
    story: 'Textbooks fail to excite today\'s generation. LearnSphere integrates standard curricula into highly interactive VR modules. We have partnered with 30 school districts in Texas and plan to expand to 200 more by next school semester.',
    fundingTimeline: [
      { month: 'Jan', amount: 50000 },
      { month: 'Feb', amount: 120000 },
      { month: 'Mar', amount: 200000 },
      { month: 'Apr', amount: 280000 },
      { month: 'May', amount: 350000 },
      { month: 'Jun', amount: 420000 },
    ],
  },
  {
    id: 's6',
    name: 'Verdant Pack',
    tagline: '100% home-compostable food packaging created from upcycled agricultural cellulose.',
    description: 'Verdant Pack creates strong, waterproof, and heat-resistant containers using local farming crop waste, degrading naturally within 45 days in household compost piles.',
    logo: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=100&h=100&q=80',
    coverImage: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    founder: 'Oliver Sterling',
    founderImage: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=150&h=150&q=80',
    industry: 'Consumer Products',
    fundingGoal: 1000000,
    amountRaised: 890000,
    daysLeft: 9,
    minInvestment: 300,
    expectedEquity: 0.10,
    location: 'Vancouver, Canada',
    teamSize: 14,
    monthlyRevenue: 52000,
    customers: 120,
    category: 'Consumer Products',
    backers: 910,
    story: 'Verdant Pack replaces plastic and toxic PFAS packaging. By partnering with multi-regional food delivery chains, we have already saved 2 million single-use plastic boxes from landfills. Help us scale our raw fiber refinement plants.',
    fundingTimeline: [
      { month: 'Jan', amount: 120000 },
      { month: 'Feb', amount: 250000 },
      { month: 'Mar', amount: 410000 },
      { month: 'Apr', amount: 600000 },
      { month: 'May', amount: 770000 },
      { month: 'Jun', amount: 890000 },
    ],
  }
];

export const successStory = {
  id: 'story1',
  name: 'Solace Robotics',
  founder: 'Elena Rostova',
  founderImage: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=250&h=250&q=80',
  logo: 'https://images.unsplash.com/photo-1546776310-eef45dd6d63c?auto=format&fit=crop&w=100&h=100&q=80',
  coverImage: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1200&q=80',
  tagline: 'From Crowd Seed to $45M Series A and Global Medical Distribution.',
  quote: "LaunchPadX completely changed our destiny. By raising $1.8M directly from our initial users, doctors, and tech advocates, we went into production without losing our voting board seats. Today, our rehabilitation exoskeletons are in 180 clinics globally.",
  fundingAchieved: '$1,800,000',
  goalPercentage: '180%',
  growthMetrics: {
    revenue: '$14.2M ARR',
    customers: '25,000+ patients treated',
    teamSize: '84 engineers & clinical researchers',
  },
  chartData: [
    { year: '2023 (Pre-Seed)', funding: 1.8, revenue: 0.1 },
    { year: '2024 (Series A)', funding: 12.0, revenue: 3.4 },
    { year: '2025 (Expansion)', funding: 12.0, revenue: 9.8 },
    { year: '2026 (Present)', funding: 12.0, revenue: 14.2 },
  ]
};

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'David Kross',
    role: 'Principal Angel Investor',
    company: 'Nexus Ventures',
    quote: 'Investing on LaunchPadX feels like having institutional venture dealflow in my pocket. The vetting process is rigorous, and tracking my equity returns is entirely automated and transparent.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&h=100&q=80',
    rating: 5,
    type: 'investor',
  },
  {
    id: 't2',
    name: 'Amina Al-Mansoor',
    role: 'Co-founder & CEO',
    company: 'Helix Medical Technologies',
    quote: 'We avoided early-stage predatory term sheets by launching on LaunchPadX. Having 1,200 small-ticket advocates who want to see our bio-printers succeed is way more valuable than one quiet investor.',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=100&h=100&q=80',
    rating: 5,
    type: 'founder',
  },
  {
    id: 't3',
    name: 'Sarah Jenkins',
    role: 'Portfolio Manager',
    company: 'Capitalize Group',
    quote: 'The reporting dashboards on LaunchPadX make compliance and stakeholder updates stress-free. Every quarterly progress report is standardized and easily accessible.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&h=100&q=80',
    rating: 5,
    type: 'investor',
  },
  {
    id: 't4',
    name: 'Kenji Takahashi',
    role: 'Founder',
    company: 'Sora Satellites',
    quote: 'LaunchPadX brought us 2.4x our target funding. The network effect of this platform allowed us to sign distribution partnerships in three new countries during the campaign itself.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&h=100&q=80',
    rating: 5,
    type: 'founder',
  }
];

export const articles: Article[] = [
  {
    id: 'a1',
    title: 'Startup Funding Guide: Which Path is Right For You?',
    summary: 'An in-depth breakdown comparing Venture Capital, Angel Syndicate Networks, Bank Loans, and Equity Crowdfunding.',
    date: 'June 24, 2026',
    author: 'Liam Sterling',
    category: 'Guides',
    readTime: '6 min read',
    coverImage: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'a2',
    title: 'How to Craft a Winning Pitch Deck: A 10-Slide Blueprint',
    summary: 'The exact slides you need to capture investor interest in under 3 minutes, featuring visual examples from solopreneurs to unicorns.',
    date: 'June 18, 2026',
    author: 'Elena Rostova',
    category: 'Pitch Decks',
    readTime: '8 min read',
    coverImage: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'a3',
    title: 'Demystifying Equity Crowdfunding: Compliance and Mechanics',
    summary: 'Understanding the SEC regulations, Reg CF boundaries, investor limit guidelines, and tax reporting duties.',
    date: 'June 10, 2026',
    author: 'Marcus Vance',
    category: 'Regulations',
    readTime: '11 min read',
    coverImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'a4',
    title: 'Understanding Startup Valuation Methods for Crowd Investors',
    summary: 'How to calculate pre-money vs post-money values using the Berkus method and scorecard systems.',
    date: 'June 05, 2026',
    author: 'Sophia Varga',
    category: 'Valuations',
    readTime: '7 min read',
    coverImage: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'a5',
    title: 'Community-Driven Growth: The Power of Founders as Educators',
    summary: 'Why startups that engage their community with transparent progress logs achieve 3x customer retention.',
    date: 'May 28, 2026',
    author: 'Dr. Helen Chen',
    category: 'Growth',
    readTime: '5 min read',
    coverImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=600&q=80',
  }
];
